### ISSUE TITLE
Unfortunately, I think it does not work on Blender 2.93.3 and 3.0.0-alpha

### ISSUE THREAD

**Issue by walterlv** [ChristinaRika/EasyHDRI#2]
I installed the EasyHDRI by clicking the `Install...` button, but no tab appeared on my context bar which is toggled using the key `N`. After installing it, a message is shown as below:

```
Modules Installed () from 'D:\\WIP\\Downloads\\Default\\EasyHDRI.zip' into 'C:\\Users\\lvyi\\AppData\\Roaming\\Blender Foundation\\Blender\\2.93\\scripts\\addons'
```

![image](https://user-images.githubusercontent.com/9959623/132269743-dd09dfe2-7f57-4a24-9993-43be7b997cd3.png)

The files are actually in the right directory:

![image](https://user-images.githubusercontent.com/9959623/132269995-4d25de12-f972-41d1-a7bf-e4d4acc25956.png)

Could you please give me some suggestions for fixing this issue?

**Comment by ChristinaRika** [comment]
Oh! Exactly, after installing this plugin, the hieraochy should look like this:
**...//Blender Foundation//Blender//2.93//scripts//addons//EaseHDRI.py**
![image](https://user-images.githubusercontent.com/46781233/132270555-444e1d47-09f5-4307-b35a-dd8234f6f928.png)

**Comment by walterlv** [comment]
@ChristinaRika Thanks for your reply.

I've tried to move the EasyHRDI.py file to exactly the addons folder and restarted the Blender, but it still didn't load.

![image](https://user-images.githubusercontent.com/9959623/132321027-d5554fab-2f66-4382-ae55-c58076a02867.png)

![image](https://user-images.githubusercontent.com/9959623/132321379-c85112a2-3076-4da6-aaa5-92f35a31c01e.png)

**Comment by ChristinaRika** [comment]
@walterlv 
Oh, I think it's my problem. I added a plugin description at head of py code, add these code will sove your problem.
![image](https://user-images.githubusercontent.com/46781233/132331976-447a92e3-6a2c-42cd-9a5c-b7b13b953ec5.png)
p.s. by using this plugin, please ensure your plugin is enabled(**preference->add-ons**)

**Comment by walterlv** [comment]
@ChristinaRika Thanks a lot for help helping me find out the issue. I actually forgot to check the EasyHRDI in the add-ons after moving the py file out of the folder.

So the critical problem is that it cannot be located in a subdirectory of add-ons.

By the way, I've tested your new source code and nothing helped because the bl_info exists in your released zip file.
